// Code generated by "enumer -type=Mutability -text -transform=title-lower"; DO NOT EDIT.

package scimtag

import (
	"fmt"
	"strings"
)

const _MutabilityName = "readWritereadOnlyimmutablewriteOnly"

var _MutabilityIndex = [...]uint8{0, 9, 17, 26, 35}

const _MutabilityLowerName = "readwritereadonlyimmutablewriteonly"

func (i Mutability) String() string {
	if i < 0 || i >= Mutability(len(_MutabilityIndex)-1) {
		return fmt.Sprintf("Mutability(%d)", i)
	}
	return _MutabilityName[_MutabilityIndex[i]:_MutabilityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MutabilityNoOp() {
	var x [1]struct{}
	_ = x[ReadWrite-(0)]
	_ = x[ReadOnly-(1)]
	_ = x[Immutable-(2)]
	_ = x[WriteOnly-(3)]
}

var _MutabilityValues = []Mutability{ReadWrite, ReadOnly, Immutable, WriteOnly}

var _MutabilityNameToValueMap = map[string]Mutability{
	_MutabilityName[0:9]:        ReadWrite,
	_MutabilityLowerName[0:9]:   ReadWrite,
	_MutabilityName[9:17]:       ReadOnly,
	_MutabilityLowerName[9:17]:  ReadOnly,
	_MutabilityName[17:26]:      Immutable,
	_MutabilityLowerName[17:26]: Immutable,
	_MutabilityName[26:35]:      WriteOnly,
	_MutabilityLowerName[26:35]: WriteOnly,
}

var _MutabilityNames = []string{
	_MutabilityName[0:9],
	_MutabilityName[9:17],
	_MutabilityName[17:26],
	_MutabilityName[26:35],
}

// MutabilityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MutabilityString(s string) (Mutability, error) {
	if val, ok := _MutabilityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MutabilityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mutability values", s)
}

// MutabilityValues returns all values of the enum
func MutabilityValues() []Mutability {
	return _MutabilityValues
}

// MutabilityStrings returns a slice of all String values of the enum
func MutabilityStrings() []string {
	strs := make([]string, len(_MutabilityNames))
	copy(strs, _MutabilityNames)
	return strs
}

// IsAMutability returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mutability) IsAMutability() bool {
	for _, v := range _MutabilityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Mutability
func (i Mutability) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Mutability
func (i *Mutability) UnmarshalText(text []byte) error {
	var err error
	*i, err = MutabilityString(string(text))
	return err
}
