// Code generated by "enumer -type=Uniqueness -text -transform=lower"; DO NOT EDIT.

package scimtag

import (
	"fmt"
	"strings"
)

const _UniquenessName = "noneserverglobal"

var _UniquenessIndex = [...]uint8{0, 4, 10, 16}

const _UniquenessLowerName = "noneserverglobal"

func (i Uniqueness) String() string {
	if i < 0 || i >= Uniqueness(len(_UniquenessIndex)-1) {
		return fmt.Sprintf("Uniqueness(%d)", i)
	}
	return _UniquenessName[_UniquenessIndex[i]:_UniquenessIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UniquenessNoOp() {
	var x [1]struct{}
	_ = x[None-(0)]
	_ = x[Server-(1)]
	_ = x[Global-(2)]
}

var _UniquenessValues = []Uniqueness{None, Server, Global}

var _UniquenessNameToValueMap = map[string]Uniqueness{
	_UniquenessName[0:4]:        None,
	_UniquenessLowerName[0:4]:   None,
	_UniquenessName[4:10]:       Server,
	_UniquenessLowerName[4:10]:  Server,
	_UniquenessName[10:16]:      Global,
	_UniquenessLowerName[10:16]: Global,
}

var _UniquenessNames = []string{
	_UniquenessName[0:4],
	_UniquenessName[4:10],
	_UniquenessName[10:16],
}

// UniquenessString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UniquenessString(s string) (Uniqueness, error) {
	if val, ok := _UniquenessNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UniquenessNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Uniqueness values", s)
}

// UniquenessValues returns all values of the enum
func UniquenessValues() []Uniqueness {
	return _UniquenessValues
}

// UniquenessStrings returns a slice of all String values of the enum
func UniquenessStrings() []string {
	strs := make([]string, len(_UniquenessNames))
	copy(strs, _UniquenessNames)
	return strs
}

// IsAUniqueness returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Uniqueness) IsAUniqueness() bool {
	for _, v := range _UniquenessValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Uniqueness
func (i Uniqueness) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Uniqueness
func (i *Uniqueness) UnmarshalText(text []byte) error {
	var err error
	*i, err = UniquenessString(string(text))
	return err
}
